export const PANEL_SEARCH_CATALOG = 'Visualize.SearchCatalog'
export const PANEL_DATASET_DETAILS = 'Visualize.DatasetDetails'
export const PANEL_DATASET_WMS_LAYERS = 'Visualize.DatasetWMSLayers'
export const PANEL_CLIMATE_INDICATORS = 'Visualize.ClimateIndicators'
export const PANEL_PLOTLY = 'Visualize.Plotly'
export const DEFAULT_SELECTED_KEY = 'frequency'
