// platform
export const PLATFORM_SECTION_ACCOUNT_MANAGEMENT = 'PLATFORM_SECTION_ACCOUNT_MANAGEMENT';
export const PLATFORM_SECTION_EXPERIENCE_MANAGEMENT = 'PLATFORM_SECTION_EXPERIENCE_MANAGEMENT';
export const PLATFORM_SECTION_MONITOR = 'PLATFORM_SECTION_MONITOR';
export const PLATFORM_SECTION_SEARCH_DATASETS = 'PLATFORM_SECTION_SEARCH_DATASETS';
export const PLATFORM_SECTION_WORKFLOWS = 'PLATFORM_SECTION_WORKFLOWS';
export const PLATFORM_SET_SECTION = 'PLATFORM_SET_SECTION';
// Visualize
export const VISUALIZE_SET_MAP_MANIPULATION_MODE = 'Visualize.VISUALIZE_SET_MAP_MANIPULATION_MODE';
export const VISUALIZE_MODE_VISUALIZE = 'MapControls.MODE_VISUALIZE';
export const VISUALIZE_MODE_GRAPHS = 'MapControls.MODE_GRAPHS';
export const VISUALIZE_MODE_JOB_MANAGEMENT = 'MapControls.MODE_REGION_SELECTION';
export const VISUALIZE_CHART_PANEL = 'CHART_PANEL';
export const VISUALIZE_LAYER_SWITCHER_PANEL = 'LAYER_SWITCHER_PANEL';
export const VISUALIZE_INFO_PANEL = 'INFO_PANEL';
export const VISUALIZE_MAP_CONTROLS_PANEL = 'MAP_CONTROLS_PANEL';
export const VISUALIZE_TIME_SLIDER_PANEL = 'TIME_SLIDER_PANEL';
// monitor
export const MONITOR_SET_JOBS = 'MONITOR_SET_JOBS';
export const JOB_FAILED_STATUS = 'ProcessFailed';
export const JOB_SUCCESS_STATUS = 'ProcessSucceeded';
export const JOB_STARTED_STATUS = 'ProcessStarted';
// workflow wizard
export const WORKFLOW_CHOOSE_PROCESS = 'WORKFLOW_CHOOSE_PROCESS';
export const WORKFLOW_SET_PROCESSES = 'WORKFLOW_SET_PROCESSES';
export const WORKFLOW_SET_PROVIDERS = 'WORKFLOW_SET_PROVIDERS';
export const WORKFLOW_CHANGE_STEP = 'WORKFLOW_CHANGE_STEP';
export const WORKFLOW_GET_FIRST_STEP = 'WORKFLOW_GET_FIRST_STEP';
export const WORKFLOW_GET_LAST_STEP = 'WORKFLOW_GET_LAST_STEP';
export const WORKFLOW_GET_NEXT_STEP = 'WORKFLOW_GET_NEXT_STEP';
export const WORKFLOW_STEP_PROCESS = 'WORKFLOW_STEP_PROCESS';
export const WORKFLOW_STEP_INPUTS = 'WORKFLOW_STEP_INPUTS';
export const WORKFLOW_STEP_RUN = 'WORKFLOW_STEP_RUN';
export const WORKFLOW_SET_WPS_PROVIDER = 'WORKFLOW_SET_WPS_PROVIDER';
export const WORKFLOW_SET_ACTIVE_PROCESS_INPUTS = 'WORKFLOW_SET_ACTIVE_PROCESS_INPUTS';
export const WORKFLOW_SET_ACTIVE_PROCESS_VALUES = 'WORKFLOW_SET_ACTIVE_PROCESS_VALUES';
// Visualize
// TODO Delete
export const PANEL_SEARCH_CATALOG = 'Visualize.SearchCatalog';
export const PANEL_DATASET_DETAILS = 'Visualize.DatasetDetails';
export const PANEL_DATASET_WMS_LAYERS = 'Visualize.DatasetWMSLayers';
export const PANEL_CLIMATE_INDICATORS = 'Visualize.ClimateIndicators';
export const PANEL_PLOTLY = 'Visualize.Plotly';
export const DEFAULT_SELECTED_KEY = 'frequency';
// Pagination
export const PER_PAGE_OPTIONS = [5, 10, 25];
export const PER_PAGE_INITIAL_INDEX = 0;
// WPS processes and forms
export const BOOLEAN = '//www.w3.org/TR/xmlschema-2/#boolean';
export const STRING = '//www.w3.org/TR/xmlschema-2/#string';
export const NETCDF = 'ComplexData';
export const LABEL_NETCDF = 'LABEL_NETCDF';
export const LABEL_SHAPEFILE = 'LABEL_SHAPEFILE';
export const LABEL_FEATURE_IDS = 'LABEL_FEATURE_IDS';
