// platform
export const PLATFORM_SECTION_ACCOUNT_MANAGEMENT = 'PLATFORM_SECTION_ACCOUNT_MANAGEMENT';
export const PLATFORM_SECTION_EXPERIENCE_MANAGEMENT = 'PLATFORM_SECTION_EXPERIENCE_MANAGEMENT';
export const PLATFORM_SECTION_MONITOR = 'PLATFORM_SECTION_MONITOR';
export const PLATFORM_SECTION_SEARCH_DATASETS = 'PLATFORM_SECTION_SEARCH_DATASETS';
export const PLATFORM_SECTION_WORKFLOWS = 'PLATFORM_SECTION_WORKFLOWS';
export const PLATFORM_SET_SECTION = 'PLATFORM_SET_SECTION';
// TODO DELETE
export const PLATFORM_SECTION_VISUALIZE = 'PLATFORM_SECTION_VISUALIZE';
export const PLATFORM_SECTION_OLCOMPONENT = 'PLATFORM_SECTION_OLCOMPONENT';


// monitor
export const MONITOR_SET_JOBS = 'MONITOR_SET_JOBS';

// workflow wizard
export const WORKFLOW_CHOOSE_PROCESS = 'WORKFLOW_CHOOSE_PROCESS';
export const WORKFLOW_SET_PROCESSES = 'WORKFLOW_SET_PROCESSES';
export const WORKFLOW_SET_PROVIDERS = 'WORKFLOW_SET_PROVIDERS';
export const WORKFLOW_CHANGE_STEP = 'WORKFLOW_CHANGE_STEP';
export const WORKFLOW_GET_LAST_STEP = 'WORKFLOW_GET_LAST_STEP';
export const WORKFLOW_STEP_PROCESS = 'WORKFLOW_STEP_PROCESS';
export const WORKFLOW_STEP_INPUTS = 'WORKFLOW_STEP_INPUTS';
export const WORKFLOW_STEP_RUN = 'WORKFLOW_STEP_RUN';
export const WORKFLOW_SET_WPS_PROVIDER = 'WORKFLOW_SET_WPS_PROVIDER';
export const WORKFLOW_SET_ACTIVE_PROCESS_INPUTS = 'WORKFLOW_SET_ACTIVE_PROCESS_INPUTS';
export const WORKFLOW_SET_ACTIVE_PROCESS_VALUES = 'WORKFLOW_SET_ACTIVE_PROCESS_VALUES';

// Visualize
export const PANEL_SEARCH_CATALOG = 'Visualize.SearchCatalog';
export const PANEL_DATASET_DETAILS = 'Visualize.DatasetDetails';
export const PANEL_DATASET_WMS_LAYERS = 'Visualize.DatasetWMSLayers';
export const PANEL_CLIMATE_INDICATORS = 'Visualize.ClimateIndicators';
export const PANEL_PLOTLY = 'Visualize.Plotly';
export const DEFAULT_SELECTED_KEY = 'frequency';
export const SET_WMS_LAYER = 'Visualize.SET_WMS_LAYER';
